sources:
  - name: airstats
    schema: raw
    tables:
      - name: airports 
        identifier: airports

      - name: airport_comments
        identifier: airport_comments

      - name: runways
        identifier: runways